---
- name: Install CopyQ
  become: true
  ansible.builtin.package:
    name: copyq
    state: "{{ copyq_ver }}"

- name: Add CopyQ autostart to Sway config
  ansible.builtin.lineinfile:
    path: "/home/{{ workstation_user }}/.config/sway/config"
    line: 'exec pgrep -x copyq || copyq'
  notify: Reload Sway configuration
  when: WM == "sway"

- name: Comment out lines with $mod+v that do not contain 'copyq'
  ansible.builtin.lineinfile:
    path: "/home/{{ workstation_user }}/.config/sway/config"
    regexp: '^(?!\s*#).*\$mod\+v(?!.*copyq).*$'
    line: '# \g<0>'
    backrefs: yes
  when: WM == "sway"

- name: Add CopyQ keybinding to Sway config
  ansible.builtin.lineinfile:
    path: "/home/{{ workstation_user }}/.config/sway/config"
    line: 'bindsym $mod+v exec copyq toggle'
    regex: '^(?!\s*#).*bindsym.*\$mod\+v.*copyq$'
  notify: Reload Sway configuration
  when: WM == "sway"

