---
# tasks file for the role
- name: Ping
  ansible.builtin.ping:

- name: Install git
  package:
    name: "{{ git_package_name }}"
    state: present
  become: true
  tags: git

- name: Install pip
  package:
    name: "{{ pip_package_name }}"
    state: present
  become: true
  tags: pip

- name: Manage ansible package
  package:
    name: "{{ ansible_package_name }}"
    state: "{{ ansible_package_state }}"
  become: true
  when: ansible_package_manage | bool
  tags: ansible
