---
# tasks file for the role
- name: Ping
  ansible.builtin.ping:

- name: Install git
  package:
    name: "{{ git_package_name }}"
    state: present
  become: true
  tags: git

- name: Install pip
  package:
    name: "{{ pip_package_name }}"
    state: present
  become: true
  tags: pip
