---
- name: Import Kubernetes naming tasks
  import_tasks: k8s_tools.yml
  when: K8S_TOOLS | bool

- name: Import DBeaver installation tasks
  import_tasks: dbeaver.yml
  when: dbeaver_ver | length > 0
