- name: Import Kubernetes naming tasks
  import_tasks: k8s_tools.yml
  when: K8S_TOOLS | bool

- name: Import DBeaver installation tasks
  import_tasks: dbeaver.yml
  when: dbeaver_ver | length > 0

- name: Import Sway configuration tasks
  import_tasks: sway.yml
  when: WM | lower == "sway"

- name: Import CopyQ installation tasks
  import_tasks: copyq.yml
  when: copyq_ver | length > 0
  tags: copyq

- name: Import screenshot tool
  import_tasks: tool_screenshot.yml
  when: screenshot_tool | length > 0
