---
- name: Install screenshot tools
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ screenshot_tool.split('_') }}"

- name: Comment out lines with bindsym that do not contain command
  ansible.builtin.lineinfile:
    path: "/home/{{ workstation_user }}/.config/sway/config"
    regexp: "^(?!\\s*#).*{{ screenshot_bindsym | escape_regex }}(?!.*{{ screenshot_tool }}).*$"
    line: '# \g<0>'
  #regexp: '^(?!\s*#).*\$mod\+v(?!.*copyq).*$'
    backrefs: yes
  when: WM == "sway"

- name: Set screenshot keybinding
  ansible.builtin.lineinfile:
    path: "/home/{{ workstation_user }}/.config/sway/config"
    line: 'bindsym {{ screenshot_bindsym }} exec {{ screenshot_command }} #{{ screenshot_tool }}'
    regex: '^(?!\s*#).*bindsym.*#{{ screenshot_tool }}$'
  notify: Reload Sway configuration
  when: WM == "sway"

